### ISSUE TITLE
Missing ftest.h

### ISSUE THREAD

**Issue by Frogsmune** [nemtrif/utfcpp#109]
Missing ftest.h in /utfcpp/extern/ftest

How to fix it:

You already have it in [your own repository linked here.](https://github.com/nemtrif/ftest/blob/c4ad4af0946b73ce1a40cbc72205d15d196c7e06/ftest.h)
You can add it from there. At least it worked for me. Else building process fails on ubuntu.

**Comment by nemtrif** [comment]
I am not sure what you are asking. Yes, ftest is an external dependency, and if you want to run utf8 cpp tests, make sure to include the submodules when doing the clone (https://stackoverflow.com/questions/3796927/how-do-i-git-clone-a-repo-including-its-submodules)

If you don't want to run utf8 cpp tests, there is nothing to build - it is a header-only library.

**Comment by Elvyria** [comment]
Confusion comes from the fact that GitHub doesn't include submodules inside source code release assets.
This problem also complicates packaging process for Linux distributions, because here's how they are usually structured:
```sh
version: 3.2.5
depends: package1, package2, ...
url: "https://github.com/nemtrif/utfcpp/archive/refs/tags/v${version}.tar.gz"
fetch() { curl -o "$url"  } # usually implicit and omitted
build() { cmake .... } # can often be also be implicit and omitted
```
As you can see, packages that are structured in such simple (preferable) way have no distinction between git or any other source archive, and expect a complete package.

Submodules are not ideal for distribution:
* What if the submodule repository is not available anymore?
* What if submodule forcefully rewrote it's git history and commit hashes don't align anymore? (no idea honestly)
* What if `git` is not available? (architecture, internet access)
* `git clone` by default doesn't clone submodules and there's no clear, verbal indication that something is missing.
* Do submodules even allow to be distributed? (licenses)
 ...

Since this is not the first time such issue was raised, may i recommend you to manually pack everything for release or setup a GitHub action to do it automatically? This might seem like a GitHub crutch, but it's a common practice.
 
Hopefully this helps with confusion.

**Comment by nemtrif** [comment]
Thanks, @Elvyria . For version 4 I will go with a very different build model for the library. There is no need for regular users to build tests and samples.
