### ISSUE TITLE
utf-8 to json encoding

### ISSUE THREAD

**Issue by omascia** [nemtrif/utfcpp#28]
Some utility function to convert a whole utf-8 string to json encoding (and the reverse) where all non ascii characters are expected to be encoded as for instance \u00e4 would be super useful, the way json constructs are at the heart of remote API nowadays (see https://graph.microsoft.com for instance).

**Comment by nemtrif** [comment]
I am open to the idea, but am struggling to imagine a use case. Parsing JSON is more than handling \u escaped text, and JSON libraries (such as https://github.com/nlohmann/json ) already handle \u escapes. What would be a real-life situation that utfcpp library is used for handling JSON strings?

**Comment by omascia** [comment]
Hi,
Sorry to reply so late, unfortunately I only received a followup email when you closed the thread today, and not when you kindly commented 12 days ago...
The use case was precisely in a in-house JSON parsing piece of code, not using a third-party JSON parsing library. But anyway, my initial question was a bit moot and you were right struggling to imagine a use case. :) In addition graph.microsoft.com do correctly support exchanging Json encoded, as per the specification in UTF-8, it just is that their documentation lacks on some areas and lead to believe their required \u encoding for proper exchange, which wasn't the case in the end.
Closed is the right status for this conversation, indeed. :)

**Comment by aman-rohilla** [comment]
Sir I have a use case I am struglling from a long time to convert json generated continuous string back to the actual unicode character. E.g. \u00c3\u00b0 is ð but parsing this with rapidjson or json cpp or nlohmann/json all converted the \u string to Ã° which is correctly not accurate. We can get the actual unicode char by using utf8::is_valid from your library. I'm am able to achieve this by converting \u to \x from the attached u2x.txt file. I append each \u unit of 6 chars and then append to a string (s) and check after appending two \u units, if the string (s) has become a utf8 valid codepoints. If you see in u2x.txt file that I can not write all the possible combinations. The current u2x file could have served in a good manner but recently I found that jsoncpp library convertes unicode character to utf8 codepoints in a different manner. For Example, jsoncpp converts ð to \u00f0 and \u00f0 can be converted back to ð by just replacing \u00 by \x but  jsoncpp converts 😊 to \ud83d\ude0a which can not be converted back to 😊 because I can convert \u00F0\u009F\u0098\u008A to 😊 but not \ud83d\ude0a to 😊 as I can't write conversion of \ud83d to \xd83d in u2x file. It would be greatly appreciated if you could provide some way to convert \u combined strings to correct unicode char. Thank you
[u2x.txt](https://github.com/nemtrif/utfcpp/files/7492626/u2x.txt)
e
