### ISSUE TITLE
Allow building without exceptions

### ISSUE THREAD

**Issue by manhnt9** [nemtrif/utfcpp#35]
Our project disable exceptions in compiler. It would be very helpful if you make a patch to enable/disable it easily. Suggested changes:

- Add new CMake option for exceptions.
- If the option is set, add a compile definition
- In library code, check for the definition and throw or terminate application with exception, or ignore

Thanks!

**Comment by devshgraphicsprogramming** [comment]
The `unchecked` namespace exists for that.

However we need an `unchecked` version of  `replace_invalid`
https://github.com/nemtrif/utfcpp/blob/master/source/utf8/checked.h#L99

AFAIK, that function doesn't even seem to throw.

**Comment by nemtrif** [comment]
@manhnt9 : You can compile with exceptions disabled without me changing anything in the CMake files. Just be sure to include "utf8/unchecked.h" instead of "utf8.h" and use the API from unchecked namespace. Make sure to use is_valid function to check your input first. Perhaps I should update the documentation to be more explicit about this use case.

To @devshgraphicsprogramming  point, replace_invalid is not available in the unchecked namespace. The "checked" version can throw if the replacement character is invalid, so I can't just move it to the unchecked namespace, but I can write an unchecked version of replace_invalid and probably should.

**Comment by devshgraphicsprogramming** [comment]
+1 for the `unchecked::replace_invalid`

**Comment by manhnt9** [comment]
+1 for fully no-exception compatible, nice project!
Haven't convinced by any utf8 lib so far since there're too many. But this one looks nice and clean.
Very admirable. Will use it soon.

**Comment by nemtrif** [comment]
Release 3.1 contains unchecked::replace_invalid() and tests with disabled exceptions.

**Comment by manhnt9** [comment]
Thanks @nemtrif.
But @devshgraphicsprogramming we forgot about `find_invalid`. I've reported 2 functions missing in the issue https://github.com/buildaworldnet/IrrlichtBAW/issues/264 but somehow we forgot it here.
@nemtrif would you mind providing this for us as well? I'm very grateful for it.

**Comment by nemtrif** [comment]
@manhnt9 : I know it is not obvious and I should do something about it, but it is possible to call utf8::find_invalid() from "unchecked" code, as it is really implemented in core.h which is included by unchecked.h. For an example, look at the usage of utf8::is_valid() from no-exceptions tests: https://github.com/nemtrif/utfcpp/blob/82c674b7a7aff3f2845e8eb17d0d9f790b629799/tests/test_unchecked_api.cpp#L155

**Comment by manhnt9** [comment]
Ah OK I've found `find_invalid` in `core.h`. I think we're good. I'm gonna continue the work.
Thanks again @nemtrif.
