### ISSUE TITLE
Using enable_testing like it is used there is an antipattern

### ISSUE THREAD

**Issue by Nic30** [nemtrif/utfcpp#73]
You should not use any extra variables and you should use `-DCMAKE_BUILD_TYPE=Debug` instead to activate tests.
https://raymii.org/s/tutorials/Cpp_project_setup_with_cmake_and_unit_tests.html
https://github.com/nemtrif/utfcpp/blob/master/CMakeLists.txt#L10

Due to this issue the antlr4-cpp runtime is having hard times.
https://github.com/antlr/antlr4/pull/2913

**Comment by ceztko** [comment]
For me there's nothing wrong in having a variable controlling doing or not doing tests and tests should be performed in both Debug/Release builds. The problem here is that gtest is invasive and forces by default `/MT`. I had a similar problem and I changed it to debug `/MD` in my [tree](https://github.com/ceztko/utfcpp/commit/3307f5ccf0d8f3738aab2025765a99c33b65eb8f). I don't know what you are doing in antlr but utfcpp is an header only library, and antlr should use that way, not including the `CMakeLists.txt` in their build system. If they are including it in their build system for good reasons they should just disable tests externally, or tell gtest to use `/MD` as already discovered in your link.

**Comment by Nic30** [comment]
OK, I understand the idea behind.
